import { faCaretDown, faSeedling } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import Head from 'next/head'
import Image from 'next/image'
import QnaPill from '../components/QnaPill'
import styles from '../styles/Home.module.css'

const QuestionsAndAnswer = [
  {   question: 'Intelligence', 
      answer: 'answer' },

  {   question: 'Sentience', 
      answer: 'answer' },

  {   question: 'Social contract', 
      answer: 'answer' },

  {   question: 'I dont care, I want my steak!', 
      answer: 'I dont know how to tell you that you should be a person that cares about the impacts of their choices' },
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-[#060b37] open-sans text-gray-200'>
        <div className='mx-4 py-4 flex flex-row items-center'>
          <div onClick={{/**/}} className='flex flex-row items-center'>
            <FontAwesomeIcon className='w-16' icon={faSeedling} />
            <h1 className='text-2xl  mx-2 font-extrabold'>Why-Veganism</h1>
          </div>
          <p className='items-end align-bottom justify-self-end right-0'></p>
          

        </div>
      <div className='text-center bg-[#091153] flex flex-col py-8 h-screen'>
        <div className='mx-64 text-xl'>
          Alright, lets start off with a pretty fundamental question.
          <h1 className='text-4xl my-8'>What is the <span className='font-bold'>morally relevant </span> 
          difference between humans and animals
          that makes it morally okay to turn <span className='font-bold'>animals</span> into hamburgers but <span className='font-bold'>not humans</span>?
          </h1>
          <div ></div>
        </div>

        {QuestionsAndAnswer.map(qa => <QnaPill question={qa.question} answer={qa.answer}/>)}

        
      </div>

      </div>
      
      <p></p>
    </>

  )
}
